services:
  # PostgreSQL database for User service
  user.db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: UserDb
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - eshop

  # Redis cache for User service
  user.cache:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - user-cache-data:/data
    networks:
      - eshop

  # RabbitMQ for messaging
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # RabbitMQ port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - eshop

volumes:
  user-db-data:
  user-cache-data:

networks:
  eshop:
    name: eshop